kind: Deployment
apiVersion: apps/v1
metadata:
  name: halo-service-v1
  namespace: $NAMESPACE
  labels:
    app: halo-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: halo-service
      version: v1
  template:
    metadata:
      labels:
        app: halo-service
        version: v1
    spec:
      volumes:
        - name: volume-1qyeu6
          persistentVolumeClaim:
            claimName: halo-volume
      containers:
        - name: container-7kev9j
          image: johnniang/halo-$USER:$BUILD_NUMBER
          ports:
            - name: http-halo
              containerPort: 8090
              protocol: TCP
          volumeMounts:
            - name: volume-1qyeu6
              mountPath: /root/.halo
          livenessProbe:
            httpGet:
              path: /
              port: 8090
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8090
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

