kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: halo-volume
  namespace: $NAMESPACE
  annotations:
    kubesphere.io/creator: "admin"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: halo-pvc
  storageClassName: csi-standard

