kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: halo-volume
  namespace: $NAMESPACE
  annotations:
    kubesphere.io/creator: "$USER"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-standard

