kind: Service
apiVersion: v1
metadata:
  name: halo-service
  namespace: $NAMESPACE
  labels:
    app: halo-service
    version: v1
spec:
  ports:
    - name: http-halo
      protocol: TCP
      port: 8090
      targetPort: 8090
  selector:
    app: halo-service
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster

